<?php
echo $this->render('menu.phtml');
$this->form->setAction($this->url());
?>

<div class="user-form form-cnt">
	<h2 class=form-title><?php echo($this->newEntry)?'Add User':'Change User';?></h2>
	<?php 
	if($this->userExist) {
		echo '<div class="error-name"><p>This username already exists.</p></div>';
	}
	echo $this->form; ?>
</div>

<script>
$( document ).ready(function() {
	function checkform() 
	{
		if(confirm('Are you sure that you want to delete this partner?') == true){
			return true;
		}
		return false;
	}
	$('#delete').click(checkform);
});
</script>